export const datosTest = [
  {
    titulo: "Inception",
    anio: "2010",
    director: "Christopher Nolan",
    genero: "Ciencia Ficción",
    tipo: "Película",
    rating: "5",
    vista: true,
  },
  {
    titulo: "Breaking Bad",
    anio: "2008",
    director: "Vince Gilligan",
    genero: "Drama",
    tipo: "Serie",
    rating: "5",
    vista: true,
  },
  {
    titulo: "Spider-Man: Across the Spider-Verse",
    anio: "2023",
    director: "Joaquim Dos Santos",
    genero: "Animación",
    tipo: "Película",
    rating: "5",
    vista: false,
  },
  {
    titulo: "The Bear",
    anio: "2022",
    director: "Christopher Storer",
    genero: "Comedia",
    tipo: "Serie",
    rating: "4",
    vista: false,
  },
  {
    titulo: "Parasite",
    anio: "2019",
    director: "Bong Joon-ho",
    genero: "Drama",
    tipo: "Película",
    rating: "5",
    vista: true,
  },
  {
    titulo: "Shingeki no Kyojin",
    anio: "2013",
    director: "Tetsurō Araki",
    genero: "Anime",
    tipo: "Serie",
    rating: "5",
    vista: false,
  },
];
